[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\v/home/renzo)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\x11\0\0\0?\0\0\x3\x18\0\0\x3r\0\0\0\x11\0\0\0?\0\0\x3\x18\0\0\x3r\0\0\0\0\0\0\0\0\x6@\0\0\0\x11\0\0\0?\0\0\x3\x18\0\0\x3r)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(600 0)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///home/renzo/2026-04-14%2012-14-29.mp4
times=0
